### ISSUE TITLE
Titles instead of numbers

### ISSUE THREAD

**Issue by lez** [arthurfranca/anips#1]
How about breaking the tradition of NIP numbering and using short, memorable names for anips?
Or both.
```
anip/editing.md
```
or
```
anip/01-editing.md
```

I'm sure there are many who are just bad in remembering numbers.

**Comment by arthurfranca** [comment]
Maybe I will change this later. Though using number for now similar to the main repo plus a random suffix to avoid collisions in case someone else happens to create another ANIPs repo (or fork this one) and then adds conflicting ANIP-01, ANIP-02 etc.

So its `ANIP-01-<random characters>` for now. That's why the ANIP-01 filename is `01-566886fe01ee5.md`
